# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required

matrix:
  include:
   - os: linux
     r: release
   - os: linux
     r: devel
     env: R_CODECOV=true

cache: 
  packages: TRUE

before_install:
  - R -e 'install.packages("devtools")'

r_packages:
  - data.table
  - shiny
  - shinythemes
  - MASS
  - methods
  - stats
  - utils
  - graphics
  - grDevices
  - tools
  - magrittr
  - rmarkdown
  - robustbase
  - ggplot2

r_github_packages:
  - jrowen/rhandsontable
  - rlbarter/superheat
  - yihui/knitr
  - r-lib/covr
  - r-lib/testthat
  - r-lib/vdiffr
  - r-lib/pkgdown
  - rstudio/shinytest
  
use_bioc: true

bioc_packages:
  - BiocGenerics
  - RProtoBufLib
  - flowCore
  - ncdfFlow
  - cytolib
  - flowWorkspace
  
warnings_are_errors: false

after_success:
  -  if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
  
env:
 global:
   - CRAN: http://cran.rstudio.com
   - BIOC_USE_DEVEL="FALSE"

addons:
  apt:
    packages:
      - libhdf5-dev
  
