// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CellCounts_character
IntegerMatrix CellCounts_character(List data, List combinations);
RcppExport SEXP COMPASS_CellCounts_character(SEXP dataSEXP, SEXP combinationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< List >::type combinations(combinationsSEXP);
    __result = Rcpp::wrap(CellCounts_character(data, combinations));
    return __result;
END_RCPP
}
// CellCounts
IntegerMatrix CellCounts(List x, List combos);
RcppExport SEXP COMPASS_CellCounts(SEXP xSEXP, SEXP combosSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type combos(combosSEXP);
    __result = Rcpp::wrap(CellCounts(x, combos));
    return __result;
END_RCPP
}
