# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CellCounts_character <- function(data, combinations) {
    .Call(COMPASS_CellCounts_character, data, combinations)
}

.CellCounts <- function(x, combos) {
    .Call(COMPASS_CellCounts, x, combos)
}

