# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CellCounts <- function(x, combos) {
    .Call('COMPASS_CellCounts', PACKAGE = 'COMPASS', x, combos)
}

